## This notebook is used to Calculate Page Ranking.

In [8]:
import numpy as np

In [9]:
x = np.array([1,5,2])
y = np.array([7,4,1])
x+y

# M is the transfer matrix, there are three nodes.
M = np.matrix( ((0,0,0), (0.5, 0,0), (0.5,1,1)) )

# now compute the stochastic telejump matrix
S=(3,3)
A = 0.7*M + 0.3/3*np.ones(S)


# initial vector
r0=np.matrix([1,1,1])


print np.linalg.norm(r0)



1.73205080757


In [10]:
# compute the stable distribution of node weight

r0=np.matrix([1,1,1])
r=A*r0.T
eps=1e-8
while (np.linalg.norm(r-r0)>eps):
    r0=r
    r=A*r0
    
print r


[[ 0.3  ]
 [ 0.405]
 [ 2.295]]


In [69]:
a = np.matrix('1,2;3,4')
print a

# this is how you access the entry in the matrix- M[m,n]
print a[0,1]

# this is how you find the dimension of the matrx: using numpy.shape-->return a tuple typed data
print np.ndim(a)
dim= np.shape(a)
row = dim[0]
col =dim[1]
print "matrix dimension :", row, col

# this is another way to find the matrix dim
print "row", len(a)
print "col", len(a.T)

# how to concatenate two matrix along y dimension
print np.concatenate((a, np.identity(row)), axis=1)


[[1 2]
 [3 4]]
2
2
matrix dimension : 2 2
row 2
col 2
[[ 1.  2.  1.  0.]
 [ 3.  4.  0.  1.]]
[[1 2]
 [3 4]]


In [86]:
# Some utility functions for matrix inversion

# swap two rows in a matrix
def swap_rows(M, x, y):
    M[[y,x]]=M[[x,y]]
    return M

a = np.matrix('1,2;3,4;5,6')
b=swap_rows(a, 0, 2)
print a
print b


[[5 6]
 [3 4]
 [1 2]]
[[5 6]
 [3 4]
 [1 2]]


In [31]:
# Function to compute the inverse of matrix X

def inverse(X):
    dim= np.shape(X)
    row = dim[0]
    col =dim[1]
     
    Y = np.concatenate((X, np.identity(row)), axis=1)
    
    for j in range(col):
        for i in range(row):
            if i!=j:
                if Y[i,j]!=0:
                    
                    

IndentationError: expected an indented block (<ipython-input-31-4b21dc6c16fa>, line 4)